fix(sidepanel): fixed sidepanel max width (#DS-2314)
koobiq/angular-components pull request #141
Opened 2024-07-17 11:55 UTC by sk8knut

2024-07-18 09:44 UTC, NikGurev requested changes

2024-07-18 09:44 UTC, NikGurev commented on packages/components/sidepanel/sidepanel.scss
> +        max-width: 100%;
Точно нужно сюда max-width?

Вижу что эти стили как будто нигде не используются. Может, всё -таки на основной класс `sidepanel-container`?

2024-07-18 09:44 UTC, NikGurev commented on packages/components/sidepanel/sidepanel.scss
> -            max-width: kbq-css-variable(sidepanel-size-small-width);
думаю, стоит оставить  max-width для конкретных размеров

2024-07-18 10:04 UTC, sk8knut commented on packages/components/sidepanel/sidepanel.scss
> -            max-width: kbq-css-variable(sidepanel-size-small-width);
https://youtrack.ptsecurity.com/issue/DS-2314 судя по задаче я сделал все правильно) в задаче указан как раз large sidepanel

2024-07-18 10:06 UTC, sk8knut commented on packages/components/sidepanel/sidepanel.scss
> +        max-width: 100%;
почему не используются, как раз они и используются для left и right сайдпанелей)
<img width="1728" alt="Снимок экрана 2024-07-18 в 13 05 37" src="https://github.com/user-attachments/assets/79692cda-a584-4d24-a55b-bb009be4a8a6">

2024-07-19 07:59 UTC, NikGurev commented on packages/components/sidepanel/sidepanel.scss
> -            max-width: kbq-css-variable(sidepanel-size-small-width);
так, а зачем тогда мы убрали max-width для других размеров? наверное, все-таки нужно оставить

2024-07-19 08:01 UTC, sk8knut commented on packages/components/sidepanel/sidepanel.scss
> -            max-width: kbq-css-variable(sidepanel-size-small-width);
@NikGurev оки, верну для всех размеров, кроме large

2024-07-19 08:53 UTC, NikGurev approved these changes

2024-07-22 13:47 UTC, merged