fix(file-upload): fixed long files names (#DS-2641)
koobiq/angular-components pull request #147
Opened 2024-07-18 11:26 UTC by sk8knut

2024-07-18 12:04 UTC, NikGurev reviewed
![image](https://github.com/user-attachments/assets/ca230d94-9350-42ef-9c09-381f4461ae75)

2024-07-18 13:00 UTC, sk8knut commented
@NikGurev добавил проверку на длину и если вдруг называние настолько длинное, что не влезает в блок - меняется его направление, чтобы было видно конец названия файла

2024-07-19 07:48 UTC, NikGurev requested changes
![image](https://github.com/user-attachments/assets/635e9862-a5cf-4ce6-89a8-c4729ad4d5fd)
Сейчас вижу, что если действительно очень большое название, то отображается так
Думаю, стоит показывать, хотя бы 1 символ от start части

имя файла: `eberhard-grossgasteiger-cgEbku0EbOg-unsplasheberhard-grossgasteiger-cgEbku0EbOg-unsplasheberhard-grossgasteiger-cgEbku0EbOg-unsplasheberhard-grossgasteiger-cgEbku0EbOg-unsplash.jpg`

2024-07-19 07:59 UTC, sk8knut commented
> ![image](https://private-user-images.githubusercontent.com/42917304/350306187-635e9862-a5cf-4ce6-89a8-c4729ad4d5fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzYyMjgsIm5iZiI6MTcyMTM3NTkyOCwicGF0aCI6Ii80MjkxNzMwNC8zNTAzMDYxODctNjM1ZTk4NjItYTVjZi00Y2U2LTg5YTgtYzQ3MjlhZDRkNWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA3NTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNTgwZjMxMWFiMDY2Nzg3OWU1ZTIyYTBiYzhlYWRmMDMxMDc0NWQ0ZjU5OGZkODdlMTkzMTJlMzBhZTQxMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i9SvzOvtSpBj8dOd3wp2o-Xuovr6IEu6cJTWXLO0adM) Сейчас вижу, что если действительно очень большое название, то отображается так Думаю, стоит показывать, хотя бы 1 символ от start части
> 
> имя файла: `eberhard-grossgasteiger-cgEbku0EbOg-unsplasheberhard-grossgasteiger-cgEbku0EbOg-unsplasheberhard-grossgasteiger-cgEbku0EbOg-unsplasheberhard-grossgasteiger-cgEbku0EbOg-unsplash.jpg`

думаю это вопрос стоит уточнить у дизайнеров @rmnturov

2024-07-19 12:04 UTC, rmnturov commented
Ожидаемый результат. Обрезание должно быть в середине @sk8knut 

это из гайда по загрузчику. вики /pages/viewpage.action?pageId=100047464
<img width="697" alt="изображение" src="https://github.com/user-attachments/assets/8c5af746-3ef0-477b-9b08-8b449603289a">

2024-07-19 12:05 UTC, rmnturov requested changes
Сделайте, плих, обрезание длинного текста по середине. Так будет видно начало файла и его расширение

2024-07-23 08:38 UTC, NikGurev commented
вроде получше ,  но текст обрезается не посередине

2024-07-23 08:38 UTC, NikGurev reviewed
вроде получше , но текст обрезается не посередине

2024-07-24 10:37 UTC, rmnturov requested changes
Хотелось бы обрезать по середине и чтобы еще менялось положение многоточия при изменении ширины блока

Так вот совсем не по середине
![изображение](https://github.com/user-attachments/assets/eadd7717-aa42-432a-8469-7931b2ea852e)

2024-07-24 10:42 UTC, rmnturov commented
Положение сообщения об ошибке неправильное. Вот такой нужно отступ
https://www.figma.com/design/UqWu6SiPskcZYImS8ANdbO/File-Upload-Error?node-id=0-1&t=fv75K0PnRQu6Gclx-1
![изображение](https://github.com/user-attachments/assets/bdfdc622-298c-4a45-bc57-ae322e2feff3)

2024-07-30 03:17 UTC, rmnturov approved these changes
Супер! @sk8knut

2024-07-30 07:54 UTC, NikGurev approved these changes

2024-07-30 07:56 UTC, merged