feat: added prettier support for html, xml, svg files (#DS-2653)
koobiq/angular-components pull request #152
Opened 2024-07-19 08:33 UTC by artembelik

2024-07-19 09:43 UTC, NikGurev requested changes

2024-07-19 09:43 UTC, NikGurev commented on packages/components/file-upload/multiple-file-upload.component.html
> -                            {{ separatedCaptionText[0] }}<label kbq-link pseudo [disabled]="disabled" [tabIndex]="-1" [for]="inputId">{{ config.browseLink }}<ng-container *ngTemplateOutlet="inputTemp
здесь нужно заигнорить и не переность, потому что переносы добавляются лишние отступы
@lskramarov подтверди пожалуйста

2024-07-19 11:48 UTC, lskramarov commented on packages/components/file-upload/multiple-file-upload.component.html
> -                            {{ separatedCaptionText[0] }}<label kbq-link pseudo [disabled]="disabled" [tabIndex]="-1" [for]="inputId">{{ config.browseLink }}<ng-container *ngTemplateOutlet="inputTemp
да, все так

2024-07-19 12:15 UTC, artembelik commented on packages/components/file-upload/multiple-file-upload.component.html
> -                            {{ separatedCaptionText[0] }}<label kbq-link pseudo [disabled]="disabled" [tabIndex]="-1" [for]="inputId">{{ config.browseLink }}<ng-container *ngTemplateOutlet="inputTemp
@NikGurev всю строку? этот перенос видно на демо?

2024-07-19 12:38 UTC, NikGurev commented on packages/components/file-upload/multiple-file-upload.component.html
> -                            {{ separatedCaptionText[0] }}<label kbq-link pseudo [disabled]="disabled" [tabIndex]="-1" [for]="inputId">{{ config.browseLink }}<ng-container *ngTemplateOutlet="inputTemp
проверил, в браузере не отображается, но лишний отступ всё равно добавляется

проверить можно открыв текст загрузчика в dev-tools

![image](https://github.com/user-attachments/assets/b4250a4a-112c-40d6-bd89-609520622c82)

2024-07-19 13:06 UTC, artembelik commented on packages/components/file-upload/multiple-file-upload.component.html
> -                            {{ separatedCaptionText[0] }}<label kbq-link pseudo [disabled]="disabled" [tabIndex]="-1" [for]="inputId">{{ config.browseLink }}<ng-container *ngTemplateOutlet="inputTemp
это никак не влияет на верстку, предлагаю оставить как есть
что думаете?

![image](https://github.com/user-attachments/assets/04816200-27b6-4588-b3bd-0af79ae920b4)

2024-07-19 13:49 UTC, NikGurev commented on packages/components/file-upload/multiple-file-upload.component.html
> -                            {{ separatedCaptionText[0] }}<label kbq-link pseudo [disabled]="disabled" [tabIndex]="-1" [for]="inputId">{{ config.browseLink }}<ng-container *ngTemplateOutlet="inputTemp
тоже не заметил проблем, браузер отрабатывает корректно, даже для случая когда ссылка посередине строки
![chrome_ww8o3tfSEK](https://github.com/user-attachments/assets/f62374c1-9146-43a6-9c62-f8f808bae767)

@lskramarov

2024-07-19 13:52 UTC, NikGurev approved these changes

2024-07-19 14:04 UTC, lskramarov commented on packages/components/file-upload/multiple-file-upload.component.html
> -                            {{ separatedCaptionText[0] }}<label kbq-link pseudo [disabled]="disabled" [tabIndex]="-1" [for]="inputId">{{ config.browseLink }}<ng-container *ngTemplateOutlet="inputTemp
В китайском локали пробела быть не должно:
![image](https://github.com/user-attachments/assets/185f31d4-7f11-47b4-8a21-187d513bf3eb)

2024-07-22 09:45 UTC, artembelik commented on packages/components/file-upload/multiple-file-upload.component.html
> -                            {{ separatedCaptionText[0] }}<label kbq-link pseudo [disabled]="disabled" [tabIndex]="-1" [for]="inputId">{{ config.browseLink }}<ng-container *ngTemplateOutlet="inputTemp
@lskramarov поправил

2024-07-22 10:30 UTC, lskramarov approved these changes

2024-07-22 10:33 UTC, merged