feat(welcome): added icon-items (#DS-2636)
koobiq/angular-components pull request #155
Opened 2024-07-22 12:18 UTC by sk8knut

2024-07-23 08:48 UTC, NikGurev requested changes

2024-07-23 08:48 UTC, NikGurev commented on apps/docs/src/app/components/documentation-items.ts
> +                    apiId: 'icon-item',
`apiId` лучше оставить тот же иначе ломается вкладка api : https://koobiq-next--prs-155-vldyr0zc.web.app/components/icon-item/api

2024-07-23 09:29 UTC, NikGurev approved these changes

2024-07-24 09:24 UTC, cm4fan approved these changes

2024-07-24 09:25 UTC, merged