Feat/ds 2335
koobiq/angular-components pull request #184
Opened 2024-07-31 11:25 UTC by NikGurev

## Summary
Open actionbar on hover/focus

## List of notable changes:

- **updated**actionbar layout - separated fade gradient block from action buttons
- **fixed** layout - height of codeblock header
- **fixed** fade gradient colors in design tokens

## What should reviewers focus on?

2024-07-31 11:40 UTC, artembelik commented on packages/components/code-block/code-block.component.ts
> +    _codeFiles: KbqCodeFile[];
```suggestion
    private _codeFiles: KbqCodeFile[];
```

2024-08-01 05:52 UTC, rmnturov commented
@NikGurev а почему ссылки на превью нет, знаешь?

2024-08-01 08:23 UTC, NikGurev commented
Видимо, потому что не в мастер целюсь

2024-08-02 08:45 UTC, artembelik approved these changes

2024-08-02 09:10 UTC, lskramarov approved these changes

2024-08-02 12:18 UTC, vitalyozza commented
@NikGurev на Safari вот такое:

https://github.com/user-attachments/assets/50cd40fb-d3a5-4338-8d34-edf0534b4360

2024-08-02 12:23 UTC, vitalyozza commented
> @NikGurev на Safari вот такое:
> 
>  Screen.Recording.2024-08-02.at.15.16.34.mov

Еще уточню: у секции "Описание работы и возможности" есть контролы, а у других секций почему-то пропадают на Safari.

2024-08-05 11:23 UTC, artembelik commented on packages/components/code-block/code-block.component.ts
> +            if (!this.hasFocus) {
а в какой момент он `false`?

2024-08-05 11:28 UTC, NikGurev commented on packages/components/code-block/code-block.component.ts
> +            if (!this.hasFocus) {
@artembelik когда фокус пришёл не с клавиатуры

2024-08-05 11:29 UTC, artembelik commented on packages/components/code-block/code-block.component.ts
> +            if (!this.hasFocus) {
мб переменную соответсвенно назвать?)

2024-08-05 11:30 UTC, artembelik commented on packages/components/code-block/code-block.component.ts
> +        this.hoverSubscription.unsubscribe();
а нам точно нужно переподписываться при изменении входных параметров?

2024-08-05 11:34 UTC, NikGurev commented on packages/components/code-block/code-block.component.ts
> +        this.hoverSubscription.unsubscribe();
это для кейса когда количество файлов меняется. Когда например был один, а стало несколько, то подписка больше не нужна

2024-08-05 11:36 UTC, artembelik approved these changes

2024-08-05 13:39 UTC, NikGurev commented on packages/components/code-block/code-block.component.ts
> +        this.hoverSubscription.unsubscribe();
поправил подписки:
- подписываемся если нет хедера.
- по `onShowMoreClick` нужно только открыть , с подписками ничего не делать , т.к.  она уже инициализирована где нужно
- если появился хедер, то отписываемся
- если изменился массив входных файлов, но он удовлетворял и удовлетворяет условию `noHeader`, то продолжать слушать события

2024-08-06 07:14 UTC, rmnturov requested changes
Не могу попасть фокусом на кнопки при tab-навигации @NikGurev 
macOS Firefox
https://github.com/user-attachments/assets/fdaa8f3f-15c2-41e6-ab13-40be240acffa

2024-08-07 10:38 UTC, rmnturov approved these changes

2024-08-07 11:13 UTC, lskramarov approved these changes

2024-08-07 11:13 UTC, lskramarov commented on packages/components/code-block/code-block.component.html
> +            [style.opacity]="this.actionbarHidden ? 0 : null"
лишний this

2024-08-07 12:50 UTC, merged