feat(tooltip): components theming with CSS-vars (#DS-2840)
koobiq/angular-components pull request #279
Opened 2024-09-11 17:14 UTC by sk8knut

2024-09-12 09:10 UTC, NikGurev requested changes

2024-09-12 09:10 UTC, NikGurev commented on packages/components/tooltip/_tooltip-theme.scss
>  // FIXME: @use properties are used, which are most likely not applied. Need to check
коммент нужно удалить, если получилось разобраться

2024-09-13 06:27 UTC, sk8knut commented on packages/components/tooltip/_tooltip-theme.scss
>  // FIXME: @use properties are used, which are most likely not applied. Need to check
+ удалил лишние импорты

2024-09-13 08:00 UTC, NikGurev approved these changes

2024-09-13 09:03 UTC, merged