feat: added accordion (#DS-2932)
koobiq/angular-components pull request #341
Opened 2024-10-02 13:36 UTC by lskramarov

2024-10-08 07:11 UTC, lskramarov commented
@vitalyozza нужна картинка для доков:
![image](https://github.com/user-attachments/assets/351d62e2-495e-4a41-b1bf-a4a4e744038f)

2024-10-08 08:47 UTC, NikGurev requested changes
@lskramarov навигация с клавиатуры работает некорректно, посмотри пожалуйста. При переключении активного элемента с помощью стрелок, триггер почему-то не переключается.

![chrome_bqX7UXF1hc](https://github.com/user-attachments/assets/64a5abfe-d0b6-4ffc-a224-208b363bc6dc)

2024-10-08 08:53 UTC, lskramarov commented
> @lskramarov навигация с клавиатуры работает некорректно, посмотри пожалуйста. При переключении активного элемента с помощью стрелок, триггер почему-то не переключается.

@NikGurev это мак, сафари ?

у меня норм:
![chrome_OumKFatrde](https://github.com/user-attachments/assets/ecf7e41e-094a-4d5d-9f87-f8ad6690540d)

2024-10-08 15:18 UTC, pimenovoleg approved these changes

2024-10-08 17:53 UTC, vitalyozza commented
@lskramarov подготовил обложки для доков: 
---
![accordion-light](https://github.com/user-attachments/assets/dae09228-ca8e-49e8-bd7d-197f09b45fcd)
---
![accordion-dark](https://github.com/user-attachments/assets/3c949074-0a53-4721-8b94-8fcc99ad9ac8)

2024-10-08 18:15 UTC, vitalyozza commented
@lskramarov 👀 посмотрел все примеры, нашел немного моментов, которые было бы здорово пофиксить. 
Учел, что нет еще анимации.  
![image](https://github.com/user-attachments/assets/af65d467-2ac4-49b6-88b5-5d6c51bf4a7f)
1. Заметил, что почему-то в текущей сборке размер шрифта больно маленький. (на картинке выше)
2. Почему-то пункты аккордеона при нажатии на них сразу выделяются синим цветом. (на картинке выше)
3. Я бы добавил дополнительные отступы внутри примеров (сверху/снизу), чтобы область с примерами была с правильными пропорциями (как в дизайне в Figma) А то сейчас все примеры сдавлены внутри code-block-ов. (на картинке ниже)
![Screenshot 2024-10-08 at 21 13 24](https://github.com/user-attachments/assets/e830dce5-d824-49a7-989f-344443a2a9c7)
4. Еще в последней секции пункты сбились, их там два. 
![image](https://github.com/user-attachments/assets/04a75f6f-e395-473a-8bbd-b3ac7533dbdc)

2024-10-09 13:43 UTC, lskramarov commented
> @lskramarov 👀 посмотрел все примеры, нашел немного моментов, которые было бы здорово пофиксить. Учел, что нет еще анимации.  
> 1. Заметил, что почему-то в текущей сборке размер шрифта больно маленький. (на картинке выше)
> 2. Почему-то пункты аккордеона при нажатии на них сразу выделяются синим цветом. (на картинке выше)
> 3. Я бы добавил дополнительные отступы внутри примеров (сверху/снизу), чтобы область с примерами была с правильными пропорциями (как в дизайне в Figma) А то сейчас все примеры сдавлены внутри code-block-ов. (на картинке ниже)
> 4. Еще в последней секции пункты сбились, их там два.

Это пофиксил, можно смотреть

2024-10-09 13:44 UTC, lskramarov commented
Баг с навигацией нужно править в радиксе

2024-10-09 14:55 UTC, vitalyozza commented
Для темной версии слетела превьюшка:
![image](https://github.com/user-attachments/assets/601c1b31-fd68-4dfc-99c9-31f6216fe4c8)

2024-10-09 14:59 UTC, vitalyozza commented
При использовании Caption текст распологается в центре строки, не идет по 1 линии с загоовком (как это в [дизайне](https://www.figma.com/design/ummbIOg2HomaEvnBMepIF2/koobiq-guides?node-id=4646-3876&node-type=frame&t=yRv69BU0rKxQdSaD-11))
![image](https://github.com/user-attachments/assets/97fdb92d-42a9-4d65-a08e-7e98b454e5ca)

2024-10-09 15:01 UTC, vitalyozza commented
У нас еще что-то случилось с пунктами списка в рекомендациях:
![image](https://github.com/user-attachments/assets/bbfb3ad6-f007-4ec0-9818-6126e1512dc6)

Вот так на странице Radio:
![image](https://github.com/user-attachments/assets/423fe3b0-51bf-4932-91e2-20fb66b9ab10)

2024-10-09 15:03 UTC, vitalyozza commented
![image](https://github.com/user-attachments/assets/447d454d-b563-4577-9fed-32349ce71f3b)
Здесь чувствуется отсутствие корректных отступов сверху/снизу внутри секции, вот как это сделано в [дизайне](https://www.figma.com/design/ummbIOg2HomaEvnBMepIF2/koobiq-guides?node-id=4657-23345&node-type=symbol&t=yRv69BU0rKxQdSaD-11).
![image](https://github.com/user-attachments/assets/6ec925a4-7155-46cf-9321-a86441a2450b)

2024-10-10 08:35 UTC, NikGurev approved these changes
LGTM

баг с аккордеоном надо править в radix

2024-10-11 07:20 UTC, vitalyozza commented
> ![image](https://private-user-images.githubusercontent.com/109949088/375014673-447d454d-b563-4577-9fed-32349ce71f3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzE1MjMsIm5iZiI6MTcyODYzMTIyMywicGF0aCI6Ii8xMDk5NDkwODgvMzc1MDE0NjczLTQ0N2Q0NTRkLWI1NjMtNDU3Ny05ZmVkLTMyMzQ5Y2U3MWYzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQwNzIwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDBhYjI4MzIwZDE0ZGEwNmVhZDUzMGRhOThlYWRlMTM1NjBkNGY5M2I3MDQ5NWM5NmYwZTQwZjFkNDY2NTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qyh4fPTRu_ay5dvxDCtkYqOxcGcF1NUNzg6fhhwEiuw) Здесь чувствуется отсутствие корректных отступов сверху/снизу внутри секции и не те border-radius-ы, вот как это сделано в [дизайне](https://www.figma.com/design/ummbIOg2HomaEvnBMepIF2/koobiq-guides?node-id=4657-23345&node-type=symbol&t=yRv69BU0rKxQdSaD-11). ![image](https://private-user-images.githubusercontent.com/109949088/375014962-6ec925a4-7155-46cf-9321-a86441a2450b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzE1MjMsIm5iZiI6MTcyODYzMTIyMywicGF0aCI6Ii8xMDk5NDkwODgvMzc1MDE0OTYyLTZlYzkyNWE0LTcxNTUtNDZjZi05MzIxLWE4NjQ0MWEyNDUwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQwNzIwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmNlZmM1MzlhY2FlYTJlM2YzMGMzYjVlYWQ0ZDhhMTVkNTk2ZDVhN2Q3OTZlMDA4MjU1MjZmZWVjZmU4Nzk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MKb9a9sPcPyfmO_TPFgrIWSLP0p5qLLYrRlu1Cmcr9s)

@lskramarov вот этот момент только не поправили, а так все остальное супер 🙌🏻

2024-10-11 07:46 UTC, vitalyozza approved these changes
@lskramarov супер! Готово! 🎉

2024-10-11 08:11 UTC, merged