feat(docs): Updating Docs for Datepicker & Timepicker (#DS-2398)
koobiq/angular-components pull request #36
Opened 2024-05-17 09:42 UTC by vitalyozza

## Summary

Added several sections about our Datepicker and Timepicker combination

## List of notable changes: 
- packages/components/datepicker.md (added a new section at the bottom of the page)
- packages/components/timepicker.md (added a new section at the bottom of the page)

## What should reviewers focus on?
- Let's have a look at the new png example for these new sections, just tried to add a background to make these examples easier to read on each theme (light/dark)

2024-05-17 10:25 UTC, pimenovoleg approved these changes

2024-05-21 23:43 UTC, rmnturov requested changes
исправляйте картинку и вперед

2024-05-21 23:43 UTC, rmnturov commented on apps/docs/src/assets/images/timepicker/timepicker-with-datepicker.png
Косяк со скруглением картинки
<img width="394" alt="изображение" src="https://github.com/koobiq/angular-components/assets/31649219/460b65d9-498d-4192-a7a9-43bedbac0902">

2024-05-23 18:01 UTC, rmnturov approved these changes

2024-05-23 18:54 UTC, merged