Updated tokens for shadows in our components
koobiq/angular-components pull request #388
Opened 2024-10-28 12:18 UTC by vitalyozza

- Replaced `box-shadow` with `shadow`.
- Used variables instead of custom code for shadows.

2024-10-29 10:07 UTC, vitalyozza commented
@NikGurev поправил нейминг в 1 файле, вроде ничего в других местах не нужно править

2024-10-29 11:21 UTC, NikGurev approved these changes

2024-10-29 11:22 UTC, NikGurev requested changes
нужно поправить в dropdown еще файл `dropdown-tokens.scss`

2024-10-29 11:24 UTC, NikGurev approved these changes

2024-10-30 03:50 UTC, rmnturov approved these changes

2024-10-30 08:22 UTC, merged