feat(toast): toast 2.0 (#DS-2360)
koobiq/angular-components pull request #39
Opened 2024-05-20 14:10 UTC by lskramarov

2024-05-23 12:07 UTC, rmnturov requested changes
Почти все хорошо, осталось поправить пару мелких моментов

Оставил комменты и картинки в Фигме
https://www.figma.com/design/p5NPERyAUXJwzquQJGCPiB/toast-v2-%40rturov?node-id=31996-121646&t=T3LMdMbzSoiZArtv-4

2024-05-28 14:38 UTC, NikGurev commented
Переключаю фокус только через Tab
https://github.com/koobiq/angular-components/assets/42917304/c5590768-a63d-407b-9f65-cf025970366f

2024-05-30 07:08 UTC, rmnturov approved these changes

2024-05-30 14:00 UTC, pimenovoleg approved these changes

2024-05-30 14:00 UTC, merged