feat(markdown): removed marked from peerDependencies, mirgrated KbqMarkdownModule to standalone (#DS-3049)
koobiq/angular-components pull request #393
Opened 2024-10-30 14:09 UTC by artembelik

2024-10-30 14:35 UTC, NikGurev requested changes

2024-10-30 14:35 UTC, NikGurev commented on packages/components/markdown/examples.markdown.md
> +<!-- example(markdown-article) -->
вкладку examples в таком случае нужно включить

2024-10-30 14:35 UTC, NikGurev commented on packages/docs-examples/components/markdown/markdown-code/markdown-code-example.html
> +
нужно добавить в template

2024-10-30 14:35 UTC, NikGurev commented on packages/components/markdown/markdown.md
> +**Обрати внимание!** Для работы компонента, необходимо наличие [`marked`](https://github.com/markedjs/marked) зависимости:
```suggestion
**Обрати внимание!** Для работы компонента, необходимо наличие [marked](https://github.com/markedjs/marked) зависимости:
```

2024-10-30 15:02 UTC, artembelik commented on packages/docs-examples/components/markdown/markdown-code/markdown-code-example.html
> +
выглядит нечитабельно, можно в дев примерах посмотреть
предлагаю для маркдавна исключение сделать

2024-10-30 15:03 UTC, artembelik commented on packages/components/markdown/markdown.md
> +**Обрати внимание!** Для работы компонента, необходимо наличие [`marked`](https://github.com/markedjs/marked) зависимости:
если ты про отображение, то оно исправится после доработки доки, баг на это завели

2024-10-31 08:15 UTC, NikGurev commented on packages/components/markdown/markdown.md
> +**Обрати внимание!** Для работы компонента, необходимо наличие [`marked`](https://github.com/markedjs/marked) зависимости:
не, я про то что ты ссылку в код обернул, это так задумано?

![image](https://github.com/user-attachments/assets/5fb36d86-dca8-4f7b-9620-f08d8db110b7)

2024-10-31 08:18 UTC, artembelik commented on packages/components/markdown/markdown.md
> +**Обрати внимание!** Для работы компонента, необходимо наличие [`marked`](https://github.com/markedjs/marked) зависимости:
да, аналогично гитхаб делает
![image](https://github.com/user-attachments/assets/95ef08a0-8fb8-44b4-bc77-e29bd242d50c)

2024-10-31 10:10 UTC, lskramarov commented on packages/components/core/pipes/safe-html.pipe.ts
> +@Pipe({
Отдельный пайп для единичного использования `bypassSecurityTrustHtml` точно нужен ? вроде ничего не мешает сделать это сразу при получении resultHtml

2024-10-31 10:23 UTC, pimenovoleg commented on packages/components/core/pipes/safe-html.pipe.ts
> +@Pipe({
давайте такие пайпы в отдельной таске сделаем касательно безопасности.

2024-10-31 13:00 UTC, artembelik commented on packages/components/core/pipes/safe-html.pipe.ts
> +@Pipe({
> Отдельный пайп для единичного использования `bypassSecurityTrustHtml` точно нужен ?

потенциально много мест где его нужно/можно применить

2024-10-31 13:11 UTC, artembelik commented on packages/components/core/pipes/safe-html.pipe.ts
> +@Pipe({
откатил

2024-10-31 14:09 UTC, pimenovoleg approved these changes

2024-10-31 14:45 UTC, NikGurev commented on packages/components/markdown/markdown.service.ts
> +    /** Parses `Markdown` into `HTML` */
```suggestion
    /** Parses `Markdown` into `HTML` using `marked`*/
```

2024-10-31 14:49 UTC, NikGurev commented on packages/docs-examples/components/markdown/markdown-code/markdown-code-example.html
> +
не, я имел ввиду в декоратор сразу шаблона добавить? Вроде короткий код довольно
А почему нечитабельно?

2024-10-31 14:52 UTC, NikGurev approved these changes

2024-11-01 07:31 UTC, lskramarov approved these changes

2024-11-01 07:40 UTC, merged

2024-11-01 08:31 UTC, artembelik commented on packages/components/markdown/markdown.service.ts
> +    /** Parses `Markdown` into `HTML` */
обсудили в личке