chore(docs): added callouts for documentation pages
koobiq/angular-components pull request #433
Opened 2024-11-15 13:32 UTC by artembelik

2024-11-15 14:27 UTC, vitalyozza commented
@artembelik проверь пожалуйста отступы, они в фигме иные. + ставишь дополнительно внутри текста отступ снизу, что создает лишнее пустое пространство
![image](https://github.com/user-attachments/assets/1c9d0666-bcea-479b-88b8-a4e329d58650)

2024-11-15 14:30 UTC, vitalyozza commented
Если параграф вставляешь в callout, то убирай у последнего параграфа отступ снизу.

2024-11-15 14:41 UTC, sk8knut approved these changes

2024-11-18 07:37 UTC, NikGurev reviewed
Выглядит топ!
Есть пару предложений, отпишись что думаешь.

2024-11-18 07:37 UTC, NikGurev commented on apps/docs/src/styles/_callout.scss
> +        border-radius: var(--kbq-size-s) var(--kbq-size-s) 0;
команда  UX завела глобальный токен border-radius, у него такое же значение, но он больше подходит для описания бордер радиуса
```suggestion
        border-radius: var(--kbq-size-border-radius) var(--kbq-size-border-radius) 0;
```

2024-11-18 07:37 UTC, NikGurev commented on apps/docs/src/styles/_callout.scss
> +        letter-spacing: var(--kbq-md-typography-md-body-letter-spacing);
Если стили типографики раздела полностью совпадают с определенным шрифтом, то можно его напрямую использовать
```suggestion
        @extend .md-body;
```

2024-11-19 14:30 UTC, artembelik commented on apps/docs/src/styles/_callout.scss
> +        letter-spacing: var(--kbq-md-typography-md-body-letter-spacing);
использовал миксину

2024-11-19 14:30 UTC, artembelik commented
> Если параграф вставляешь в callout, то убирай у последнего параграфа отступ снизу.

@rmnturov поправил

2024-11-20 08:39 UTC, NikGurev approved these changes

2024-11-20 09:10 UTC, artembelik commented
@rmnturov нам очень понравился дизайн [этих callout](https://angular.dev/guide/directives)

![image](https://github.com/user-attachments/assets/bd50cfa5-8bf1-489e-b084-46d11055f68f)

2024-11-26 07:49 UTC, rmnturov commented
Под коллаутом маргин должен быть 24px (xxl), сейчас 20 (xl)

2024-11-26 07:49 UTC, rmnturov requested changes
Под коллаутом маргин должен быть 24px (xxl), сейчас 20 (xl)

2024-11-26 09:04 UTC, artembelik commented
> Под коллаутом маргин должен быть 24px (xxl), сейчас 20 (xl)

поправил

2024-11-26 09:18 UTC, rmnturov approved these changes

2024-11-26 09:29 UTC, merged