fix(select): dropdown positioning and sizing (#DS-3234)
koobiq/angular-components pull request #485
Opened 2024-12-19 15:42 UTC by sk8knut

Что сделано:

- ширина выпадашек (autocomplete, select, tag autocomplete, timezone, tree-select) теперь считается правильно и равна родительскому триггеру без учета бордеров
- отрицательные офсеты по оси X убраны
- добавлены правильные оффсеты Y в зависимости от позиционирование выпадашки (сверхи или снизу)
- поправлен пример автокомплита
- поправлен пример селекта с поиском

2024-12-20 19:16 UTC, artembelik commented on packages/components/core/select/constants.ts
> +export const SELECT_PANEL_PADDING_X = 0;
кажется что эта переменная больше не актуальна, мб можно удалить или пометить как `@deprecated` ?

2024-12-20 19:17 UTC, artembelik commented on packages/components/core/select/constants.ts
>  export const SELECT_PANEL_INDENT_PADDING_X = SELECT_PANEL_PADDING_X * 2;
аналогично, плюс здесь всегда будет `0`

2024-12-20 19:19 UTC, artembelik commented on packages/components/core/styles/common/_select.scss
> +            padding: var(--kbq-select-size-multiple-padding-vertical, var(--kbq-size-xs))
кажется что здесь больше не нужны фолбеки, мб удалим?

2024-12-20 19:20 UTC, artembelik commented on packages/components/form-field/form-field.scss
> +    &:before {
напомни пожалуйста, зачем бордюр перенесли в псевдо элемент?

2024-12-20 19:22 UTC, artembelik approved these changes

2024-12-21 09:27 UTC, sk8knut commented on packages/components/form-field/form-field.scss
> +    &:before {
для того чтобы не следить за вычитанием этого бордюра из падддингов, для просчета ширины выпадашек без учета бордера

2024-12-21 09:28 UTC, sk8knut commented on packages/components/core/styles/common/_select.scss
> +            padding: var(--kbq-select-size-multiple-padding-vertical, var(--kbq-size-xs))
поговорил с Никитой на неделе насчет этого, тут нужно оставить) @NikGurev

2024-12-21 09:28 UTC, sk8knut commented on packages/components/core/select/constants.ts
>  export const SELECT_PANEL_INDENT_PADDING_X = SELECT_PANEL_PADDING_X * 2;
решил пока оставить на будущее, но думаю ты прав и можно удалить)

2024-12-23 10:05 UTC, lskramarov commented on packages/components/form-field/form-field.scss
> +    &:before {
Если честно для меня "вычитать размер бордера из паддинга" более очевидно, чем бордер сделанный через абсолютно спозиционированный `:before`.

Предлагаю на синке обсудить.

2024-12-23 11:20 UTC, artembelik commented
нужно обновить метод `open()` в `select.component.ts`

```ts
this.triggerRect = this.parentFormField
  ? this.parentFormField.getConnectedOverlayOrigin().nativeElement.getBoundingClientRect()
  : this.trigger.nativeElement.getBoundingClientRect();
```

2024-12-23 11:26 UTC, NikGurev commented on packages/components/core/styles/common/_select.scss
> +            padding: var(--kbq-select-size-multiple-padding-vertical, var(--kbq-size-xs))
@artembelik тут фолбеки нужны , если разработчикам потребуется кастомизация. Например, для timezone-select

2024-12-28 12:55 UTC, NikGurev commented on packages/components/autocomplete/autocomplete-trigger.directive.ts
> +                    offsetY: 2
Добавь пожалуйста комментарий, почему именно 2

2024-12-28 12:56 UTC, NikGurev commented on packages/components/autocomplete/autocomplete.scss
> +    max-height: var(--kbq-select-panel-size-max-height,);
```suggestion
    max-height: var(--kbq-select-panel-size-max-height);
```

2024-12-28 12:56 UTC, NikGurev commented on packages/components/autocomplete/autocomplete.scss
> -    .kbq-autocomplete-panel-above & {
@vitalyozza проверь, по дизайну сходится или нет

2024-12-28 12:57 UTC, NikGurev commented on packages/components/select/select.component.ts
> +            offsetY: this.offsetY
в autocomplete можно сделать аналогично

2024-12-28 13:04 UTC, NikGurev commented on packages/components/select/select.component.ts
> +            : this.trigger.nativeElement.getBoundingClientRect();
Как вариант, чтобы дважды не вызывать `getBoundingClientRect`
```suggestion
this.triggerRect = (this.parentFormField?.getConnectedOverlayOrigin().nativeElement || this.trigger.nativeElement).getBoundingClientRect();
```

Либо
```
const originElement = this.parentFormField
    ? this.parentFormField.getConnectedOverlayOrigin().nativeElement
    : this.trigger.nativeElement;

this.triggerRect = originElement.getBoundingClientRect();
```

2024-12-28 13:05 UTC, NikGurev approved these changes

2024-12-28 13:06 UTC, NikGurev requested changes
@sk8knut посмотри тесты пожалуйста

2025-01-10 06:20 UTC, rmnturov commented
@sk8knut выравнивание/ширина поправлены. класс

2025-01-10 06:20 UTC, rmnturov approved these changes

2025-01-14 14:39 UTC, NikGurev approved these changes

2025-01-14 15:14 UTC, merged