feat(radio): New Sections for Radio Component (#DS-1483)
koobiq/angular-components pull request #91
Opened 2024-06-18 08:53 UTC by vitalyozza

## Summary

New version for Radio page 

## List of notable changes:

- Added text for new sections
- Prepared spaces for new examples

## What should reviewers focus on?

2024-06-25 08:17 UTC, vitalyozza commented
Ждем примеров от разработчиков, задача: [DS-2575](https://youtrack.ptsecurity.com/issue/DS-2575) [Docs] примеры для Radio

2024-07-04 12:55 UTC, NikGurev requested changes

2024-07-04 12:55 UTC, NikGurev commented on packages/docs-examples/components/radio/radio-content/radio-content-example.css
> +.example-radio-raw {
так как отключена инкапсуляция стилей, советую ограничить стили уникальным селектором для данного примера, потому что есть шанс , что при переключении страниц применятся стили в другом примере

2024-07-04 12:55 UTC, NikGurev commented on packages/docs-examples/components/radio/radio-size/radio-size-example.css
> +    gap: 24px;
аналогично тут

2024-07-04 12:55 UTC, NikGurev commented on packages/components/radio/radio.md
> +<!-- example -->
думаю, неактуальный комментарий

2024-07-04 16:37 UTC, NikGurev approved these changes

2024-07-05 10:02 UTC, merged